application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1:3000"

database:
  require_ssl: false

email_client:
  base_url: "http://127.0.0.1:3000"
  sender_email: "test@gmail.com"
  authorization_token: "some_token"
  timeout_ms: 5000