application:
  host: 0.0.0.0

database:
  require_ssl: false

email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "something@gmail.com"
  authorization_token: "some_token"
  timeout_ms: 5000